### ISSUE TITLE
i18n

### ISSUE THREAD

**Issue by vitormattos** [LyseonTech/libresign#2]
- [x] README in `pt_BR` and `en_US`
- [ ] doc's folder in `pt_BR` and `en_US`
- [x] Translate all text of frontend

**Comment by rakekniven** [comment]
Regarding nextcloud sync to transifex I currently cannot see if you have user nextcloud-bot to your repo with write permissions?

**Comment by vitormattos** [comment]
Permission added, waiting accept invite:

![image](https://user-images.githubusercontent.com/1079143/108209837-88e0a480-7109-11eb-8bfa-3a4036e198bc.png)

**Comment by rakekniven** [comment]
Ok, invite has been accepted.
Have you seen my review comment at https://github.com/nextcloud/docker-ci/pull/264#pullrequestreview-592161517 ?
That should be the last step.
